### PR TITLE
Feat/setup firestore

### PR DESCRIPTION
**Pull request by trungnq2k**

### CODE REVIEW

**Comment by minhnguyenphamquoc** [comment]
Please resolve commit @trungnq2k

**Comment by minhnguyenphamquoc** [comment]
A @trungnq2k please delete the `package-lock` created by "npm" command, only use yarn as it will only relies on `yarn.lock`.

**Review by trungnq2k — COMMENTED** [review]
Removed package-lock.json

**Review by minhnguyenphamquoc — APPROVED** [review]
Looks good to me!

**Pull request merged**
